"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var weather_station_ts_1 = require("./observables/weather_station.ts");
var mobile_display_ts_1 = require("./observers/mobile_display.ts");
var tv_display_ts_1 = require("./observers/tv_display.ts");
var ws = new weather_station_ts_1.default();
var tvDisplay = new tv_display_ts_1.default();
var mobileDisplay = new mobile_display_ts_1.default();
ws.addObserver(tvDisplay);
ws.addObserver(mobileDisplay);
ws.temperature = 10;
